version: '3.8'
services:
  db:
    image: mysql:8.0.21
    container_name: classchats-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: classchatsdev
      MYSQL_DATABASE: ClassChats
  
  backend:
    image: node:12.18.3
    container_name: classchats-backend
    entrypoint: bash -c "cd /classchats/ && npx tsc --watch"
    stdin_open: true
    tty: true
    environment:
      DB_DATABASE: ClassChats
      DB_USERNAME: root
      DB_PASSWORD: classchatsdev
      DB_HOST: classchats-db
    volumes:
      - type: bind  # Mount the current directory into the container
        source: ./
        target: /classchats/
        read_only: true
      - type: tmpfs  # Mount a volume into /classchats/build/ where compiled TS can live. ./build must exist on the host.
        target: /classchats/build/
