# This workflow will check that PRs use the correct style.

name: Style Check
on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check "src/**/*.ts"
